
enum entry_type
{
    function,
    variable,
    taskgroup,
    task,
    struct_data,
    supervisor,
};

const std::string entry_type_strings[] = {
    "function",
    "variable",
    "taskgroup",
    "task",
    "struct_data",
    "supervisor",
};

enum dtypes
{
    int_t,
    float_t,
    long_t,
    bool_t,
    char_t,
    string_t,
    unknown_t,
    struct_t,
    void_t,
};

const std::string dtype_strings[] = {
    "int",
    "float",
    "long",
    "bool",
    "char",
    "string",
    "unknown",
    "struct",
    "void",
};

enum kind_t
{
    root_t,
    decl_stmt,
    expr_stmt,
    cond_stmt,
    if_stmt,
    else_stmt,
    elseif_stmt,
    loop_stmt,
    compound_stmt,
    return_stmt,
    call_stmt,
    join_stmt,
    variable_stmt,
    array_stmt,
    function_decl_stmt,
    function_call_stmt,
    literal,
    variable_t,
    type_t,
    list_init,
    taskgroup_stmt,
    task_stmt,
    supervisor_stmt,
    properties_stmt,
    order_rule,
    order_node,
    array_element, // eg: arr[1][2]
    struct_decl,
    parallel_stmt,
    keyword,
    reduction_operator,
    channel_stmt,
    iterative_stmt,
    shared_rule,
    shared_node,
    task_t,
    mem_rule,
    mem_node,
    empty_expr_stmt,
    itr_type,
    selection_stmt,
};

const std::string kind_t_strings[] = {
    "root_t",
    "decl_stmt",
    "expr_stmt",
    "cond_stmt",
    "if_stmt",
    "else_stmt",
    "elseif_stmt",
    "loop_stmt",
    "compound_stmt",
    "return_stmt",
    "call_stmt",
    "join_stmt",
    "variable_stmt",
    "array_stmt",
    "function_decl_stmt",
    "function_call_stmt",
    "literal",
    "variable_t",
    "type_t",
    "list_init",
    "taskgroup_stmt",
    "task_stmt",
    "supervisor_stmt",
    "properties_stmt",
    "order_rule",
    "order_node",
    "array_element",
    "struct_decl",
    "parallel_stmt",
    "keyword",
    "reduction_operator",
    "channel_stmt",
    "iterative_stmt",
    "shared_rule",
    "shared_node",
    "task_t",
    "mem_rule",
    "mem_node",
    "empty_expr_stmt",
    "itr_type",
    "selection_stmt",
};